- name: Install git package.
  package: name=git state=present

- name: Create gitlab-runner group
  group:
    name: gitlab-runner
    state: present

- name: Add the user 'gitlab-runner' with a bash shell, appending to the group 'docker'
  user:
    name: gitlab-runner
    comment: GitLab Runner
    shell: /bin/bash
    group: gitlab-runner
    groups: docker
    append: True
    create_home: True

- name: Download gitlab-runner.
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    dest: /usr/bin/gitlab-runner
    mode: '0755'

- name: Install epel-release package.
  package: name=epel-release state=present

- name: Install python-pip package.
  package: name=python-pip state=present

- pip:
    name: python-gitlab

- pip:
    name: requests

- name: Register runner.
  gitlab_runner:
    url: "{{ api_url }}"
    api_token: "{{ api_token }}"
    description: "{{ description }}"
    registration_token: "{{ token }}"
    state: present
    active: True
    tag_list: ["{{ tag }}"]
    run_untagged: False
    locked: False